DROP TABLE IF EXISTS MEMO;

CREATE TABLE IF NOT EXISTS MEMO(
      ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      TITLE VARCHAR(50) NOT NULL,
      CONTENT VARCHAR(50)
   )

INSERT INTO MEMO(TITLE, CONTENT) 
VALUES ('test','test content'),('test2','test content2'),('test3','test content3');

SELECT * FROM MEMO;

SELECT * FROM MEMO WHERE ID=2;

UPDATE MEMO SET TITLE='공부하기', CONTENT='열심히 공부하기' WHERE ID=2;

DELETE FROM  MEMO WHERE ID=2;